# Generated by Django 2.1 on 2018-08-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180831_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='company_info',
        ),
        migrations.AddField(
            model_name='event',
            name='company_address',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='company_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='company_name',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='company_office',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='company_phone1',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='company_phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='company_web_address',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
