# Generated by Django 2.1 on 2018-08-31 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20180831_0715'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInfo',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='event_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
