# Generated by Django 2.1 on 2018-08-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180831_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='company_web_address',
            field=models.URLField(blank=True, null=True),
        ),
    ]
