# Generated by Django 2.1 on 2018-08-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180831_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
