# Generated by Django 2.1 on 2018-08-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
