# Generated by Django 2.1 on 2018-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180831_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventreview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
