# Generated by Django 2.1 on 2018-08-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
