# Generated by Django 2.1 on 2018-09-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventcategory_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcategory',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='category/images'),
            preserve_default=False,
        ),
    ]
