# Generated by Django 2.1 on 2018-09-09 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20180907_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='event',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='event_booking', to='events.Event'),
            preserve_default=False,
        ),
    ]
