# Generated by Django 2.1 on 2018-09-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180909_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
